### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by 3tz** [3tz/ganabi#1]
# Priority

- [x] SWMR read
- [x] automated logging training process
    - [x] fix Mlp not able to load weights from h5
    - [x] Automated CSIF training
- [x] keras data gen memory leak
    - [x] fixed switching to HDF5
    - [ ] multiprocessing.set_start_method('spawn', force=true)
- [ ] stateless?
- [X] extremely low accuracy after hdf5
- [X] .pkl cannot be greater than 1gb
    - [X] to be solved with multi-proc, so...
    - [X] make sure data gen uses random seed for different runs
- [X] fixed not training full dataset within one epoch.

# Miscs

- [ ] clean up
    - [ ] remove assert
    - [ ] update instructions
    - [ ] better .datalog: save # turns under each subdir
    - [ ] remove TODO/FIXME before shipping
- [ ] WTFWT compression crash
- [ ] efficency improvements
    - [ ] save hdf5 directly instead of converting from .pkl
- [ ] fix .datalog if veryfication fails
- [x] rl_env.py line 404 for rainbow agent gen
- [X] fireflower crashes?
    - [X] from utils import binary_list_to_int as b2int
- [X] investigate not enuf mem TF
- [X] test load from .h5
- [X] automated training all pickles in a directory
- [X] load checkpoint aka best model
- [X] convert batch by batch
- [X] --m default should be 0 instead of None
